#!/usr/bin/env bash

function multiplication () {

num1=$1 num2=$2

if [[ $num1 == ?(-)+([0-9]) ]]; then
   variable_num1_a=$num1
   variable_num1_b=0
elif [[ $num1 =~ ^[-+]?(\.[0-9]+|[0-9]+(\.[0-9]*)?)$ ]]; then
   variable_num1_a=${num1%.*}
   variable_num1_b=${num1#*.}
fi

if [[ $num2 == ?(-)+([0-9]) ]]
then
   variable_num2_a=$num2
   variable_num2_b=0
else
   variable_num2_a=${num2%.*}
   variable_num2_b=${num2#*.}
fi

remove_dot_num1=$(echo $variable_num1_a$variable_num1_b)
remove_dot_num2=$(echo $variable_num2_a$variable_num2_b)

result_multiplication_num1_and_num2=$(( remove_dot_num1 * remove_dot_num2))

let "result_add_num1_a_and_num2_a = result_multiplication_num1_and_num2 / 100"
let "result_add_num1_b_and_num2_b = result_multiplication_num1_and_num2 % 100"

if [[ $result_add_num1_b_and_num2_b -eq 0 ]]
then  
   echo $result_add_num1_a_and_num2_a
else
   result=$(echo $result_add_num1_a_and_num2_a.$result_add_num1_b_and_num2_b)
   echo $result
fi

}
